alarm:
  code: '1230'
dimmer:
  day_hour: 6
  day_min: 30
  day_sec: 0
  day_value: 200
  night_hour: 22
  night_min: 0
  night_sec: 0
  night_value: 33
mqtt:
  broker: 10.1.1.75
  com_topic: home/alarm/set
  fail: MQTT Messaging Failed
  pass: av
  port: 1883
  sent: ''
  state_topic: home/alarm
  username: av
piezo:
  pin: 23
screen:
  x: '800'
  y: '480'
warnings:
  backlight: '[WARNING] BACKLIGHT not connected'
  gpio: '[WARNING] GPIO not connected'
